### ISSUE TITLE
[BUG] Layout not loading

### ISSUE THREAD

**Issue by davidevanlovett** [Invvard/EZLayoutDisplay#101]
## Actual Behavior
When setting up a layout, a warning window pops telling the Hash ID doesn't exist, for default or other configurations

![image](https://user-images.githubusercontent.com/18276723/88587252-80f4d200-d00a-11ea-8d3a-a9283725ce61.png)
![image](https://user-images.githubusercontent.com/18276723/88587738-42134c00-d00b-11ea-8b0f-ce4983e88e7f.png)
![image](https://user-images.githubusercontent.com/18276723/88587762-4fc8d180-d00b-11ea-8d85-774a3b3120e7.png)

## To Reproduce

1. Copy URL from Configurator.
2. Paste it into the setting window.
3. Warning Window opens.
3. Try to change & click 'apply'
4. Warning window pops.

## Expected Behavior
Expected settings to load. 

## Specifications
  - EZLayout Version: v1.1.13
  - ErgoDox Layout Configurator URL: https://configure.ergodox-ez.com/layouts/default/latest/0
  - Operating System (incl. Version): Windows 10

**Comment by Invvard** [comment]
Hi @davidevanlovett,

I think there were a bit of overhaul on the Oryx app side. I'll investigate this as soon as possible.
I'll keep you posted.

**Comment by davidevanlovett** [comment]
Thanks! I really appreciate it, this is such a cool tool

**Comment by Invvard** [comment]
There is a [new release](https://github.com/Invvard/EZLayoutDisplay/releases/tag/1.1.4) !
Let me know if everything is OK for you :)

**Comment by davidevanlovett** [comment]
It's perfect, thank you so much!

**Comment by Voidlighter** [comment]
I'm having this very same issue, is this now too outdated to work?
