### ISSUE TITLE
[BUG] Short & concise bug description

### ISSUE THREAD

**Issue by n8craig** [Invvard/EZLayoutDisplay#107]
## Actual Behavior
There is no layout shown in the app main window, but in the settings it properly lists the layout and its various layers.

![2020-12-17 13_35_42-ErgoDox Layout](https://user-images.githubusercontent.com/62002677/102541029-1aca2380-406d-11eb-9fdd-9c0a83e59ec4.jpg)
![2020-12-17 13_36_06-Window](https://user-images.githubusercontent.com/62002677/102541005-17cf3300-406d-11eb-942f-d2368977dc51.jpg)

## To Reproduce
  1. I tried this with various layouts and the result is the same.

## Expected Behavior
I expect a layout to be displayed rather than a blank window on the main app.

## Specifications
  - EZLayout Version: [e.g. v1.1.4
  - ErgoDox Layout Configurator URL: https://configure.ergodox-ez.com/moonlander/layouts/bdopQ/latest/0
  - Operating System (incl. Version): Wi10
  - Moonlander

**Comment by Invvard** [comment]
Hi @n8craig,

Right now, the Moonlander is not supported. I have not been putting a lot of time recently in supporting other product from ZSA.
Only the ErgoDox EZ is supported.

Sorry for the let down :/
