### ISSUE TITLE
[BUG] Ergodox EZ keys show as blank

### ISSUE THREAD

**Issue by ChaoticWeg** [Invvard/EZLayoutDisplay#115]
## Actual Behavior
The layout shows up OK, but all the keys are blank on all layers

## To Reproduce
  1. Downloaded and extracted v1.2.1 from GitHub releases page
  2. Ran v1.2.1, copied layout configurator URL as below into input in Settings window
  3. The keys show up as blank, though it does correctly cycle through layers when I press space

## Expected Behavior
I think there might be something that should be showing other than the screenshot below

## Specifications
  - EZLayout Version: v1.2.1
  - ErgoDox Layout Configurator URL: https://configure.zsa.io/ergodox-ez/layouts/NpN74/latest/0
  - Operating System (incl. Version): Windows 10 Pro v2004 build 19041.1415
  
## Additional context
Brand new Ergodox EZ, just arrived a couple of days ago.

![image](https://user-images.githubusercontent.com/8321710/147881233-64242c73-410e-497b-b4d9-dbac4369024d.png)

**Comment by Invvard** [comment]
Hi @ChaoticWeg,

Thank you for reporting this issue. It seems that data model has shifted and now, it does not load the keyboard layout properly.
I'll look into this ASAP.

**Comment by Invvard** [comment]
FYI : I went deeper in my analysis and ZSA did some extensive modifications on their data model and I have to refactor the app a bit to fix this issue.

**Comment by Invvard** [comment]
I'm still working on the refactoring : there has been a cascading effect on the data model changes.
I'm currently working on loading keyboard layouts. After this, I'll have to rework the key UI template so it matches the new look.

It should not be too long until I can release the new version.

**Comment by Invvard** [comment]
Checkpoint : loading is fixed and refactored. I have some adjustments to make to my datamodel but it is almost complete.
I'm currently redesigning the UI as it is no longer working properly (well, it displays the keyboard and the layout but in a very ugly manner).

As soon as I have something acceptable, I'll release a beta so user can enjoy the app again.

Then I'll get to the unit testing and integration testing phase !

**Comment by Invvard** [comment]
At last, this "Fix" is finally done ! Sorry for the delay, but it won't disappoint.

As you can see on this screenshot, it feels more a major update than a fix 🤣
![image](https://user-images.githubusercontent.com/7305493/150464836-b7da9f3d-148e-4e58-90ad-8aade7dade46.png)

It has been like a rabbit hole : the more I fixed, the more needed to be fixed!

Expect the pre-release very soon.

**Comment by Invvard** [comment]
With your layout, here is the result :
![image](https://user-images.githubusercontent.com/7305493/150468503-05d5bbc1-ba7a-45a8-baec-dc91fd8d9d81.png)

**Comment by Invvard** [comment]
The [v1.3.0-beta](https://github.com/Invvard/EZLayoutDisplay/releases/tag/1.3.0-beta) is online !
Enjoy the fix and all the improvements !!

**Comment by ChaoticWeg** [comment]
Missed this update somehow, sorry. Looks great! Working perfectly now. Thank you for the fix!
