### ISSUE TITLE
only displays default layout

### ISSUE THREAD

**Issue by fhludlow** [Invvard/EZLayoutDisplay#62]
[2019-04-18.txt](https://github.com/Invvard/EZLayoutDisplay/files/3095825/2019-04-18.txt)
## Actual Behavior
Only displays default layout

## To Reproduce
  1.  Enter valid url
  2. display layout
  3.

## Expected Behavior
Display the layout from url

## Specifications
  - 1.01.0
  - ErgoDox Layout Configurator URL:  
https://configure.ergodox-ez.com/ergodox-ez/layouts/Xbbry/latest/0
https://configure.ergodox-ez.com/ergodox-ez/layouts/GGOZa/latest/0
  - Operating System Win 10 1809 x64

**Comment by Invvard** [comment]
From what I see in the logs, at line 892, you've pasted your URL twice :
`2019-04-18 14:41:09.1751 - DEBUG - InvvardDev.EZLayoutDisplay.Desktop.ViewModel.SettingsViewModel = Layout URL = https://configure.ergodox-ez.com/ergodox-ez/layouts/Xbbry/latest/0https://configure.ergodox-ez.com/ergodox-ez/layouts/Xbbry/latest/0`

In the URL setting field, press CTRL+A to select all, delete the value then paste your URL https://configure.ergodox-ez.com/ergodox-ez/layouts/Xbbry/latest/0 and I think you should be good to go :)

If it solved your issue, you can close it, else I'll continue to investigate.

**Comment by fhludlow** [comment]
Nah that was unfortunate, it was in there twice in that case but I've done this over and over again.  Deleted everything, redownloaded etc. In that log I started it with one url, reproduced the issue, then changed it to the double one. I did that again w/ 2 urls in this log, verified not double.
[2019-04-18_2.txt](https://github.com/Invvard/EZLayoutDisplay/files/3096048/2019-04-18_2.txt)

**Comment by Invvard** [comment]
OK thank you, I'll analyse these logs this evening or tomorrow.
Thank you for the report and sorry for the inconvenience.

**Comment by Invvard** [comment]
I just saw the issue, even without opening my IDE !
Ergodox EZ changed the URL to the configurator.
Old URL : https://configure.ergodox-ez.com/layouts/KbVp/latest/0
New URL : https://configure.ergodox-ez.com/ergodox-ez/layouts/Xbbry/latest/0

The fix is easy now. Thank you for your patience, a new release is coming !

**Comment by Invvard** [comment]
Does the new version fix your issue? (it's meant to, so I hope it does hold its promise 😄)

**Comment by fhludlow** [comment]
Yes!!  Thanks I really appreciate this app.

**Comment by Invvard** [comment]
That's great ! Enjoy the app !
