### ISSUE TITLE
[Feature request] Show custom compiled layout

### ISSUE THREAD

**Issue by cwesterlund** [Invvard/EZLayoutDisplay#64]
**Is your feature request related to a problem? Please describe.**
I have a custom layout since I have a more complicated layout with swedish characters and macros for development and such. It is not possible to create such layout with the web configurator. 

**Describe the solution you'd like**
Would be cool if you could read a layout file and parse the information, or have a file which could be edited so I could fill out my layout my self in that file. So it reads from that file instead of the web configurator. Other than that, great idea and app!

**Comment by Invvard** [comment]
Yes, that's an idea I'm thinking about since the very start of this project.
As a ErgoDox EZ user, I decided to focus on this product but I'm going to open to other layout sources and other keyboard form factor in a near future.

**Comment by cwesterlund** [comment]
Sounds great, looking forward to the upcoming features!
