### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by mmarvo** [Invvard/EZLayoutDisplay#65]
Would love to see tabs or some way of switching to another layer via the gui rather than just sequencial shifting using the spacebar.
Possibly just pressing the layer number would work for the first 10 ?
And or possibly a way of deselecting tabs from the scroll, i have several but most of them are not changing at any one time as they are for games.

Great  work btw. I have some other feature req/observations. Shall I just raise them each as a separate thing here? Don't want it to look like negative criticism...

**Comment by Invvard** [comment]
Hi @mmarvo,

Thank you for the support !

These are great ideas. I particularly like the one about deselecting layers !
I was thinking about using the mouse scroll to switch from one layer to another but using the layer number is also a very good way.
You can add your other ideas below (structure them as much as possible) and we'll discuss them.

For now, I'll add your first ideas to the "Features" project.

**Comment by mmarvo** [comment]
I had not thought of the mouse scroll, that is a great idea, indeed probably fast enough that the deselect might not be needed.

**Comment by mmarvo** [comment]
Thanks for the reply.

OK here goes with the other stuff:

it would be great if one could select  non US keyboard as an option (I know double redirect in the code sucks) however double redirect in my head is a headache, e.g.  what shows as @ on ergodex layout appears as " when I press the key due to my using UK keyboard in windows OS.

The window does not remember position on close, could this be an option? I have dual screens not sure if that complicates things.

The pin option is great. It seems to make it top window on my system, not my preferred choice of behavior...

Lastly I am confused by buttons in settings: update, apply  seems redundant choice?

Again hoping you do not see any of this as negative! Happy to clarify and the app is pinned to my screen right now :)

**Comment by Invvard** [comment]
> it would be great if one could select non US keyboard as an option (I know double redirect in the code sucks) however double redirect in my head is a headache, e.g. what shows as @ on ergodex layout appears as " when I press the key due to my using UK keyboard in windows OS.

Yes, as a Canadian Multilingual Standard user, I know the issue and I've already booked the idea : https://github.com/Invvard/EZLayoutDisplay/projects/1#card-20099176
But as you say, that's quite complex and that is going to need some heavy lifting. 

> The window does not remember position on close, could this be an option? I have dual screens not sure if that complicates things.

Ah yes, I thought of this one but it was to set the window position from the settings. At first, the window had no title bar and could not be moved around. Now, registering window position on the fly is a good idea 👍 

> The pin option is great. It seems to make it top window on my system, not my preferred choice of behavior...

I don't understand this one. Do you mean that there could be an intermediate behavior where the windows would not be on top of the System windows but would not be reduced when out of focus ?

> Lastly I am confused by buttons in settings: update, apply seems redundant choice?

Yes, you're not the first one to talk about this one... I added this button at first for development purposes so I could reload the current layout without having to change the URL at all. And it stayed there as I thought user might need it. But obviously, it's more confusing than helping. I'll hide it (it's very useful when developing !)

> Again hoping you do not see any of this as negative! Happy to clarify and the app is pinned to my screen right now :)

Nope, don't worry, every contribution is very much appreciated, especially when it's polite and constructive like yours. It's very nice to have that kind of feedback : that means I'm not the only one using it and furthermore, that users like you are enthusiastic enough about the app to take time and get it better ! I love it 😄

So thank you very much for your time and those ideas !
