### ISSUE TITLE
[BUG] Error setting URL

### ISSUE THREAD

**Issue by tazard** [Invvard/EZLayoutDisplay#84]
## Actual Behavior
When setting a URL in settings, app reports error "Almost crashed"... cat land on feet, etc... check log.

## To Reproduce
Input any config URL, eg https://configure.ergodox-ez.com/ergodox-ez/layouts/jZ7le/latest/0
Click apply
Error

## Expected Behavior
Load config

## Specifications
  - EZLayoutDisplay-v1.1.0.0
  - Windows 10
  
## Additional context
Works fine on my home PC. Error is on work PC. Suspect it is the work proxy (yeah i find it quite annoying too). Any chance of using windows proxy settings? User/pass is also an issue.

Alternately, is there a JSON/XML file or something that this app pulls that is the actual layout that I could manually download and provide to your app?

Also, I cant find the logs. Running the app in this dir "C:\Tools\EZLayoutDisplay". The config "NLog.config" seems to indicate logs should be in that dir.

Sorry if this is duplicate bug.

**Comment by Invvard** [comment]
Hi @tazard, sorry to hear about this.
I tried reproducing your issue but no luck. My money is also on your work network.

The log not appearing is odd though as it should create the directory directly when an exception occur. Have you tried to start the app in admin mode ?

You can activate the full log by following this post : https://github.com/Invvard/EZLayoutDisplay/wiki/Logging

As for the possibility to add a JSON, I haven't done it yet not because it is complex on my side but it is very complex on the user side.

**Comment by Invvard** [comment]
Hi @tazard,
Did you have the chance to activate the full log option ? If so, you can upload the files here and I'll analyse them and may be we'll be able to understand what's happening.

**Comment by tazard** [comment]
Ill try it and get back to you

**Comment by tazard** [comment]
No log files were generated running regular user or admin without commandline args. Full trace was created in /logs when adding "-loglevel=trace" switch as argument. Running app in `C:\tools\EZLayoutDisplay`. No special permissions there so far as I know.

Yep, proxy auth error.

[2019-06-11.txt](https://github.com/Invvard/EZLayoutDisplay/files/3274793/2019-06-11.txt)

Does the app cache the received JSON locally? Could I run it on a PC that has open internet access and then copy the whole folder to my work PC (or a permanently offline PC)?

**Comment by Invvard** [comment]
Hi @tazard,

Sorry for the delay, I didn't get the notification that you responded.

I'm currently thinking about changing the way settings and working items are handled.
Right now, all is managed through .NET Framework but it has some downside that are becoming annoying.

In the mean time, you can get your copy your data from this folder :
C:\Users\**{UserName}**\AppData\Local\InvvardDev\**{SubDirectoryWithVersion}**\1.0.1.0
Replace the bold parts with your information.
Copy-paste the **user.configs** file from your personal computer onto your professional computer and you should be good to go.

Keep me updated about your issue.

Sorry for the inconvenience.

**Comment by tazard** [comment]
Thanks @Invvard. Yep, I think copying the config file across is a reasonable solution. 

I found the location easy enough on my home PC. On the work PC it seemed like it hadn't created even the "C:\Users\USER\AppData\Local\InvvardDev" folder (it doesn't create it until successfully load a settings file?). 

Anyway, copying over the whole InvvardDev folder did the trick - my keyboard layout appears on the work PC (with internet access only through a proxy). Thanks for your help.
