### ISSUE TITLE
[BUG] Non Glow keys have accent colors

### ISSUE THREAD

**Issue by Invvard** [Invvard/EZLayoutDisplay#90]
## Actual Behavior
The non glowing keys get a color applied.

## Expected Behavior
A non glowing key should have the default color applied and nothing else.

## Specifications
  - EZLayout Version: v1.1
  - ErgoDox Layout Configurator URL:https://configure.ergodox-ez.com/ergodox-ez/layouts/gavQM/latest/0
  - Operating System (incl. Version): n/a

**Comment by SuperCuber** [comment]
Something that could be relevant here is that it might be an Oryx issue. When you swap keys, the lighting setting persists even if it is swapped with a non-lightable key. I have reported that bug already, and it could be affecting things here.
