### ISSUE TITLE
Detected Shine keyboard instead Glow

### ISSUE THREAD

**Issue by MaxStgs** [Invvard/EZLayoutDisplay#92]
## Actual Behavior
In settings:
Keyboard model: ErgoDox EZ Shine

## To Reproduce
  1. Buy Ergodox EZ Glow
  2. Connect this to Windows 10
  3. Open EZLayout settings

## Expected Behavior
Keyboard model: ErgoDox EZ Glow

## Specifications
  - EZLayout Version: v.1.1.0.0
  - ErgoDox Layout Configurator URL: https://configure.ergodox-ez.com/layouts/default/latest/0
  - Operating System (incl. Version): [e.g. Windows 10]
Windows 10 Version 10.0.17763.557

**Comment by Invvard** [comment]
Hi @MaxStgs,
This is not a bug (either from EZLD nor ErgoDox EZ Configurator).
The default layout is aimed at the Shine version but there's a compilation for the Glow as well.
The EZLD app doesn't rely on the compiled file or the connected device but on the JSON server through a GraphQL request directly from the Configurator web page.

If you clone it and change the target for a Glow keyboard, you'll see that everything is displayed as expected.
