### ISSUE TITLE
[Feature request] Allow keyboard shortcut combination to be changed.

### ISSUE THREAD

**Issue by jeremytbrun** [Invvard/EZLayoutDisplay#99]
I have a custom build ErgoDox (not an ErgoDox EZ) that I have been using their graphical configurator with no issues. Your software works for my layout, but I don't (by choice) have a hyper key mapped on my keyboard. Can I change the key combination that will pop open the layout viewer instead of Hyper+Space?

**Comment by Invvard** [comment]
Hello @jeremytbrun,

This feature is already planned [here](https://github.com/Invvard/EZLayoutDisplay/projects/1#card-17540464). Unfortunately, I am currently swamp with non dev related business and I have little to no free time to work on it.

In the mean time, you can change it directly in the setting file : see the HotkeyShowLayout setting.
Default is : {"modifiers":[0,1,2,4],"keycode":32}
Modifiers are : 
- 0  = Alt,
- 1 = Ctrl,
- 2 = Shift,
- 3 = OS Key  (Windows or Cmd).

KeyCode is representing the [ASCII code ](http://www.asciitable.com/index/asciifull.gif) for a key. Here it is Space and its value is 32.

So if you want to change it, let's say for "Ctrl+Shift+a", the value would be :
{"modifiers":[1,2],"keycode":97}

It is  not ideal, but that's the best I can do for now.

**Comment by jhughes01** [comment]
+1 for this feature request due to windows intercepting hyper now to advertise office 365!
